### ISSUE TITLE
New Tutorial/Guide Please

### ISSUE THREAD

**Issue by pbo1976** [PopcornTimeTV/PopcornTimeTV#105]
Hi everyone. I am not able to Build a successful version above 1.0.

Last 1.0.5 gave me a total of 92 errors in Xcode.

Can someone please make a updated guide on how to install a working version? I would really appreciate it! 

And what happened to KickAssTorrent search?

Also, any ideas on how to install Movie Box or Play Box HD onto atv4? 
Thanks

**Comment by Mr-SMG** [comment]
Also struggling to compile 1.0.3.2. with TopShelf errors. The IPA from the third parties crashes a lot, 1.0.3.1. Seems to be old layout?

**Comment by tvOSPopcorn** [comment]
KickAss search was axed after the original site was taken offline, since then all the clones of KAT have been surfacing non of them offer API support so we're unable to fetch data from that site.

PopcornTimeTV is in the process of being upgraded to support tvOS 10 and the new Movies & TV Shows API's stick by, we're working on it 👍 

@pbo1976 Movie Box & Play Box HD do not have a tvOS application.

**Comment by tomsbrinkis** [comment]
@tvOSPopcorn hey, if kickass is down, maybe we could use Putlocker API? 
The site is providing new and HD quality movies. No need for seeders ir you chose really old movie. Because sometimes the movies or shows just dont start, cuz theres no seeders. :/ 

read more about putlocker API - http://www.programmableweb.com/api/putlocker
