### ISSUE TITLE
Failed to code sign "SWXMLHash".

### ISSUE THREAD

**Issue by BilalBaydoun** [PopcornTimeTV/PopcornTimeTV#13]
Hi,

I'm getting the below error when I'm building the solution:

Failed to code sign "SWXMLHash".
Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles.

I looked on google for work around and I found this script but it didn't work for me:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end

Thank you

**Comment by FlaviaBondJamesBondsHusband** [comment]
That script will not work as it is meant for an older OS version. Pre-iOS9/tvOS9 you would need this script but since then apple has allowed distribution on devices. Please delete the project and then follow the build instructions step by step: https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime.

**Comment by BilalBaydoun** [comment]
The issue was with xcode itself I deleted xcode and reinstalled it back and it's working now fine.

Thank you for your help.
