### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by RafaleD** [PopcornTimeTV/PopcornTimeTV#146]
Hi everyone. 

As you can see on my screenshot, I can't build PopCornTime.
I've already build it (version 0.4.0) but now I can't.
I get errors.  Do you have an idea of the problem 
![capture d ecran 2016-05-30 a 16 15 58](https://cloud.githubusercontent.com/assets/7534640/15651874/87d05670-2682-11e6-8c63-a32d09f28166.png)
?

**Comment by ozkrtech** [comment]
You need to update the pods. What i do is i go into the popcorntime folder and find another folder named "script", in there you will see a file named "bootstrap". Run that and it will automatically update all your pods. After its done try to build again.

Oscar Rodriguez
IT Technician

On May 30, 2016, at 10:22 AM, Dany <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi everyone.

As you can see on my screenshot, I can't build PopCornTime.
I've already build it (version 0.4.0) but now I can't.
I get errors. Do you have an idea of the problem
[capture d ecran 2016-05-30 a 16 15 58]<https://cloud.githubusercontent.com/assets/7534640/15651874/87d05670-2682-11e6-8c63-a32d09f28166.png>
?

-

**Comment by RafaleD** [comment]
It almost works. I get less errors.

Apparently I had installed version 1.0.0 of cocoapods when we need to use the 0.39.0.
I uninstall 1.0.0 then re-install 0.39.0
Now it works !!! Yeah 

Thank you ;)

**Comment by ozkrtech** [comment]
Good to know.

Oscar Rodriguez
IT Technician

On May 30, 2016, at 11:44 AM, Dany <notifications@github.com<mailto:notifications@github.com>> wrote:


It almost works. I get less errors.

Apparently I had installed version 1.0.0 of cocoapods when we need to use the 0.39.0.
I uninstall 1.0.0 then re-install 0.39.0
Now it works !!! Yeah

Thank you ;)

-

**Comment by ynnad696** [comment]
guys i'm not able to create the .ipa because my usb issue after jailbrake, and as you guys know is not posible to compile the files and sign it with xcode because the apple tv needs to be connected to the computer , can any of you guys upload the .ipa so i can load it to my apple tv via iResign ?
thanks

**Comment by ozkrtech** [comment]
Not possible. Sorry

Oscar Rodriguez
IT Technician

On May 30, 2016, at 11:52 AM, ynnad696 <notifications@github.com<mailto:notifications@github.com>> wrote:


guys i'm not able to create the .ipa because my usb issue after jailbrake, and as you guys know is not posible to compile the files and sign it with xcode because the apple tv needs to be connected to the computer , can any of you guys upload the .ipa so i can load it to my apple tv via iResign ?
thanks

-

**Comment by RefusedFlow** [comment]
@ynnad696 We won't be compiling the project into an **.ipa** you're more than welcome to purchase a developer account yourself and sign the application but we won't.

@RafaleD Closing this issue, as you've managed to solve the problem you where having 👍
