### ISSUE TITLE
Subtitle language default

### ISSUE THREAD

**Issue by matiasloda** [PopcornTimeTV/PopcornTimeTV#157]
Hi, I was wondering if there's any chance to add at configuration menu so thing to set the default language of the subtitles?
Thanks

**Comment by buzzel** [comment]
You mean have it automatically enabled when a movie loads?

**Comment by matiasloda** [comment]
Yeah that's mi idea/suggestion.
What do you think?

**Comment by tomto147** [comment]
I was suggesting same thing few weeks before. There should be an option in settings menu to automatically display the default subtitle language as long as it is available from opensubtitles.
And one more thing... in my opionion the size of subtitles is still not OK. The biggest option of 45 is to big and the second biggest of 30 is to small. There sould be something in-between probably on 35 points.

**Comment by RefusedFlow** [comment]
@tomto147 You're more than welcome to change the subtitle typeface size in **SettingsViewController.swift**

**Comment by RefusedFlow** [comment]
@matiasloda 
**Added your request to the progress page, you can visit it here but for the time being this issue will be closed**
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress

**Comment by tomto147** [comment]
@refusedFlow
I know I can change the subtitles size in controlerview. But many times I am getting errors after swift install.swiff not able to eg. checkout 0.6.6 because of some files missing. Then I have to delete the whole repo, cline it from here and edit subtitles sizes all pver again and again... Maybe it would be easier to apply a field in the app where every user can adjust the size on appleTV itself? Same solution is beeing used in Squire App
