### ISSUE TITLE
PCTPlayerViewController UX - tvOS

### ISSUE THREAD

**Issue by FlaviaBondJamesBondsHusband** [PopcornTimeTV/PopcornTimeTV#194]
- [x] User should tap remote and then pan, triggering scrubbing. Right now as soon as user pans (may be accidental) the player will start scrubbing.
- [x] Upon pausing, a screenshot image should appear
- [x] When scrubbing, menu button should stop scrubbing and resume playback, not exit the player
- [x] Info swiper should appear after 3.0 seconds (long tap)
- [x] Info view controller re-implementation

**Comment by delut** [comment]
I think that it would be more user friendly to open a tv show in the latest season available instead of the first one.

*Actual results:*
Open the Walking Dead, taken to the second season.

*Expected results:*
Open the Walking Dead, taken to the seventh season (the last one currently available).

What do you think?

**Comment by tvOSPopcorn** [comment]
@delut That was a feature back when we were on tvOS 9, since then a majority of the application has been rewritten. We can look into adding that back into the application

**Comment by FlaviaBondJamesBondsHusband** [comment]
@delut thanks for the suggestion, it is now implemented into the latest version of the app :)
