### ISSUE TITLE
Jailbroken aTV4's

### ISSUE THREAD

**Issue by wahlmanj** [PopcornTimeTV/PopcornTimeTV#206]
Even with a paid developers account you cannot install Popcorn time on jailbroken Apple TV 4's since the USB-C is disabled after jailbreak, explain how you can export a ipa without having usb-c access via Xcode. You comment does not make sense:

> This isn't a support forum, this is an issues/suggestions page. If you post this question again you will be banned from posting any more issues. We will never distribute iPA's. Please download them at your own risk. Its not our responsibility that you do not have a developer account. You want free movies and tv shows? Pay the minor inconvenience of reloading the app every few weeks.

Also with iresign we get years of having apps jailbroken aTV4's, so again your comment makes no sense. Im not sure but with appsync it may even be permanently available on jailbroken aTV4's. I never asked anyone that develops popcorntime to distribute the ipa if you actually read the issue:

> Sorry to open this again, I am looking for a ipa only. I do not have a paid developer account. Also my USB is disabled on my aTV4 (Also I'm sure many many others have this issue) since jailbreaking it so I cannot sideload it even if I had a developer account. **I do not want or am looking for a ipa from the developers of this project.** I am looking for anyone to upload the latest ipa to a file upload site only so I can install it on my jailbroken aTV4. Please if this issue can be left open and unlocked until someone uploads it I would appreciate it. I can resign it myself no problem with iResign. Thanks again for this project and for all the hard work and support.

**Comment by FlaviaBondJamesBondsHusband** [comment]
>  I never asked anyone that develops popcorntime to distribute the ipa if you actually read the issue:

Ok lets get this straight, **THIS IS NOT A SUPPORT FORUM**. I do not care if you didn't ask one of us to distribute it, nor did I ever say you did, I said we never will so stop posting stuff on the suggestions/issues page. If you want other people to, go post it on reddit or something, it's not my responsibility. 

> Even with a paid developers account you cannot install Popcorn time on jailbroken Apple TV 4's since the USB-C is disabled after jailbreak, explain how you can export a ipa without having usb-c access via Xcode. You comment does not make sense:

Hmm ok you jailbroke your AppleTV and now you're complaining that you cannot install the app because you jailbroke your AppleTV? Here's a quick tip, *unjailbreak your AppleTV*. What do you expect me to do?
 *Oh by the way, theres a secret port on the under side of the unit that allows you to install apps to your AppleTV when jailbroken.*

As stated in my previous comment, you will now be blocked and all your open issues will be closed. Have a nice day
