### ISSUE TITLE
blank timeline screenshot 

### ISSUE THREAD

**Issue by puba** [PopcornTimeTV/PopcornTimeTV#214]
Timeline screenshot has empty image/frame inside the box, i.e just blank/black screen.  When trying to forward or rewind media, buffer circle icon is spinning endleslly. When touching the edge of  remote circle icon is displayed on timeline, indicating that media will be forwarded or rewinded for 30 sec, but in fact, it is  for 2 minutes.  I am on beta 6.

**Comment by FlaviaBondJamesBondsHusband** [comment]
> Timeline screenshot has empty image/frame inside the box, i.e just blank/black screen.

The image generation will only work on downloaded parts of the movie, otherwise, a black image will be shown. This behaviour is expected.

> When trying to forward or rewind media, buffer circle icon is spinning endleslly.

Nothing we can do about this unfortunately, you will just have to be patient

>  When touching the edge of remote circle icon is displayed on timeline, indicating that media will be forwarded or rewinded for 30 sec, but in fact, it is for 2 minutes

This issue should be fixed in the latest commit. Please update master and try again.

**Comment by puba** [comment]
Thank you very much, will do.
