### ISSUE TITLE
Downloading speed

### ISSUE THREAD

**Issue by marp04** [PopcornTimeTV/PopcornTimeTV#237]
Why always the downloading speed on desktop version is very fast and TvOS is so slow? This happen to me with any movie, and doesn't matter how many seeds/peers

**Comment by b1narygh0st** [comment]
Hello @marp04, this is because the desktop version uses a very popular and famous torrenting framework, however we don't have the same luxury as this is quite pioneer on tvOS, we had to build a torrenting framework ourselves, which is yet very recent, it did not have the time to be developed and matured as the official version had.
