### ISSUE TITLE
TV search; running found series pushes app to background

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#25]
When doing a TV show search for ' LATE ' Several late night shows appear. Selecting any of them (including e.g. Stephen Colbert Late Night ') create a blank screen and pushes the app to the background. Same counts for ' O ' for O'brien. 
My GF is a fan of Stephen, so you would do me a favor :)

**Comment by tvOSPopcorn** [comment]
@Evhelden Yeahh since Search isn't natively implemented it's not perfect, partially because it's not natively implemented into the API. I'll add this to the bugs list over on the [Wiki](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress) but in the meantime i'd recommend you add all of your shows and movies to your favourites so you don't have to search for each item every time you'd like to watch it.

I've pushed a new commit containing a few new UI changes, would love to hear any feedback.

**Comment by Evhelden** [comment]
Thanks for the reply. Are you suggesting that the search function is not working but also no longer under development?

**Comment by tvOSPopcorn** [comment]
@evhelden Unfortunately it's not currently being worked on, I will bring this up with the team to see if can get looked into though... Unless you want it fixed sooner bring a developer to the project or push a PR yourself. 😬

**Comment by Evhelden** [comment]
Thanks. I wish I could. I actually have installed Xcode for the first time for this project. I am already happy I can compile and run :) Anyway.. please check the torrents for the TVshows. On the Butter project on my MacBook all series run fine. Thanks for the great work and I will try what I can :)

**Comment by popcornMaster** [comment]
This issue has now been identified and fixed, project will be updated with the fix, thank you :)

**Comment by Evhelden** [comment]
Thank you!
