### ISSUE TITLE
tvos apple tv 4 Pagination not properly working

### ISSUE THREAD

**Issue by super20161** [PopcornTimeTV/PopcornTimeTV#274]
Pagination not properly working thank you  version 3.0.0  apple tv 4 scrolling jump to top

**Comment by FlaviaBondJamesBondsHusband** [comment]
It's as good as it's going to be

**Comment by pbo1976** [comment]
Still happening, very annoying. Everything else is pretty sweet. Although sometime the movie/show freezes (audio still going)...

**Comment by GerTeunis** [comment]
Could you elaborate why is this is how it is going to be? Still no reason why? Is it the TVMLkitchen which doesn't support it?

**Comment by tvOSPopcorn** [comment]
@GerTeunis Okay so from what I'm aware of, is that the JS broke when we re-wrote the application in Swift 3 probably something Apple changed in tvOS 10 which broke the pagination. We know the pagination is janky asf right now, and it's something we're unable to figure out and find a fix. The only possible way we could fix it right now would be to write the Media/Catalogue recipe in UIKit rather than TVML, but we sadly don't have much spare time to contemplate doing that anytime soon. You're more than welcome to submit a PR yourself

Hope that explains the issue?
