### ISSUE TITLE
Kick Ass torrent?

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#3]
Great job on the latest version, including fforward/reverse/resume functions! Question:
Since the URL for kick ass torrent is no longer working, also the feature in popcorn TV is not working. I liked playing the torrents from this source a lot. Somebody able to get this feature back alive? This URL: http://kickasstorrentsan.com seems to function.

**Comment by tomsbrinkis** [comment]
Yea, it would be awesome that someone could change torrent site, because it looks like kickass is gonna be down for a long time. Maybe lets use pirate bay?

**Comment by RefusedFlow** [comment]
@Evhelden @tomsbrinkis We actually require the use of a KickAss API rather than just scraping the website. So if you come across `http://kickasstorrentsan.com/api` a KickAss domain with support for the API then please reopen this issue but for the time being it's going to be closed as it's nothing we have control over unfortunately.
