### ISSUE TITLE
i got error with building the tvos build

### ISSUE THREAD

**Issue by maiiikell1995** [PopcornTimeTV/PopcornTimeTV#346]
I am a comple noob i follow the guide and still got these error's: Apple Mach-O Linker (ID) Warning & PBXCp Warning. popcorntime was installed on the atv and it is working okay, but whenever im at the end of a page no new movies are loading is this because of these error's? 

Let me know! 

On iOS it is working great for me! 

Keep up the good work 👌

**Comment by FlaviaBondJamesBondsHusband** [comment]
Unfortunately there are many pagination issues in the latest version (3.0.0). These have all been fixed in master and will be available when we release version 3.1.0 hopefully very soon. Keep in mind those **"Warnings"** do not mean anything. It is only when they stop the project from compiling that they become errors.

Anyway, keep an eye out for release 3.1.0 which will fix a lot of your issues!

**Comment by maiiikell1995** [comment]
Thank you for this fast reply great work! 
Can we donate or contribute somewhere?

**Comment by FlaviaBondJamesBondsHusband** [comment]
You're very welcome!

> Can we donate or contribute somewhere?

Thank you very much but we do not accept donations, we do it out of the goodness of our hearts (plus accepting donations is illegal :wink:).

As far as contributing goes, feel free to fork the repo and make a PR 😄
