### ISSUE TITLE
Req: in app update

### ISSUE THREAD

**Issue by s-dm** [PopcornTimeTV/PopcornTimeTV#347]
Is it possible to get an in app update on tvOS? So that I don't need to download and compile it on my mac and then install?

**Comment by moh0sw1** [comment]
I don't think u will be able to do that on tvOS any time soon!

On Feb 13, 2017 11:25 AM, "s-dm" <notifications@github.com> wrote:

Is it possible to get an in app update on tvOS? So that I don't need to
download and compile it on my mac and then install?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PopcornTimeTV/PopcornTimeTV/issues/347>, or mute the
thread

**Comment by tvOSPopcorn** [comment]
Unfortunately this isn't possible sorry.
