### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by nickdekruijk** [PopcornTimeTV/PopcornTimeTV#365]
I tried installing too and have similar issues. First of all the documentation seems incomplete. When doing swift install.swift I'm asked to enter a version number. Docs didn't mention this so I just picked the highest (3.0.0). During installation I get a few red messages like 
```
- `SwiftKVC (~> 3.0.1)` required by `Podfile`.
```
 In the end I also get this: 
```
Opening Xcode...
["-c", "open PopcornTime.xcworkspace"]
The file /Users/nick/Documents/XCode/PopcornTimeTV/PopcornTime.xcworkspace does not exist.
```

**Comment by puba** [comment]
latest master seems to work fine....you should update repo and update & install pod

**Comment by faiello7** [comment]
If I do that.. would I need to run the 'swift install.swift'?

thanks for the help!

**Comment by puba** [comment]
running installation script without prior updating repo and pod will do no good i.e you will get the same error msg over and over again

**Comment by nickdekruijk** [comment]
When I get this
```
# Fetching the latest verion info...
3.0.0
0.2.0-7
0.2.0-6
0.2.0-5
0.2.0-0
1.0.5
1.0.3.2
1.0.3
1.0.2.1
1.0.2
1.0.1
1.0
Enter the version number:
```
And enter 3.0.0 it doesn't work. Entering 0.2.0-7 indeed seems to work like faiello7 mentioned.
But I don't think the install script should ask it in the first place?

**Comment by moh0sw1** [comment]
Don't use the install script. Use `pod repo update; pod install;`

On Feb 27, 2017 1:25 PM, "Nick de Kruijk" <notifications@github.com> wrote:

When I get this

# Fetching the latest verion info...
3.0.0
0.2.0-7
0.2.0-6
0.2.0-5
0.2.0-0
1.0.5
1.0.3.2
1.0.3
1.0.2.1
1.0.2
1.0.1
1.0
Enter the version number:

And enter 3.0.0 it doesn't work. Entering 0.2.0-7 indeed seems to work like
faiello7 mentioned.
But I don't think the install script should ask it in the first place?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PopcornTimeTV/PopcornTimeTV/issues/365#issuecomment-282682421>,
or mute the thread

**Comment by nickdekruijk** [comment]
Shouldn't `pod repo update; pod install;` be in the documentation instead op swift install.swift then?

**Comment by tvOSPopcorn** [comment]
`pod repo update; pod install;`
Will download the necessary pods requirements and add them to the project. I'll get it added to the documentation.

**Comment by nickdekruijk** [comment]
`pod repo update; pod install;` works fine indeed. Was just confused because of the outdated Wiki
