### ISSUE TITLE
Subtitle alternatives

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#379]
PopcornTimeTV should have an alternative for using subtitle in case of the `open subtitle` is down.
Even better if the user could choose witch service to use, in case `open subtitle` is working, but the legend is unsynchronized

here are some alternatives services:
- https://isubtitles.net/
- https://www.subtitles.hr/
- http://www.moviesubtitles.org/
- http://www.subs4free.com/

there are much more...

**Comment by FlaviaBondJamesBondsHusband** [comment]
None of those websites both

a. Have an API
and 
b. Contain subtitles for episodes

OpenSubtitles, although bad, are the only public API (that we're aware of) that provides both movie/episode subtitles on a semi-consistent basis. If you find an actual subtitles API, feel free to reopen/post a new issue. Otherwise, OpenSubtitles will have to suffice
