### ISSUE TITLE
Titles fail to load if it cannot immediately fetch the page.

### ISSUE THREAD

**Issue by Kazom** [PopcornTimeTV/PopcornTimeTV#40]
Hard to explain but for example go to tv shows and type in "su" you CAN click on a title like super natural BUT if you click on a title such as it's always sunny in Philadelphia it just makes the click action then nothing happens... even waited a bit to see if it would load nada. Any ideas?

**Comment by delut** [comment]
I fixed this in my latest pull request. It was something to do with how names were passed between controllers. There are only a handful of shows that are not working now, like Lost, but this is harder to fix because of some naming conventions.

For example, Lost is referenced as "lost" in our application, but trakt.tv named it as "lost-2005" and its pretty hard to find these names.

"It's always Sunny in Philadelphia" is now working though. Some shows fail to load for different bugs, as time progresses everything will work better.

**Comment by Kazom** [comment]
Thank you so much @delut ! I can go through testing shows later this week if needed.
