### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by aboveo** [PopcornTimeTV/PopcornTimeTV#435]
- No subtitle Option while playing video
- Cannot sync subtitles with videos if more than +5 or -5
- Pausing a video and going back is still playing sound in background
- Going Back to resume video crashes app
- Rewind doesn't work

**Comment by FlaviaBondJamesBondsHusband** [comment]
> No subtitle Option while playing video

#420

> Cannot sync subtitles with videos if more than +5 or -5

If the subtitle is more than ±5s wrong, there is a problem with the subtitle

> Pausing a video and going back is still playing sound in background
> Going Back to resume video crashes app

This issue was fixed already in commit 50f1e12

> Rewind doesn't work

This is a limitation of VLCKit which supports fast forwarding but not rewinding. You can open an issue with them [here](https://code.videolan.org/videolan/VLCKit/issues)
