### ISSUE TITLE
Apple TV - Audio delay with AirPlay speaker

### ISSUE THREAD

**Issue by MatthieuTnsc** [PopcornTimeTV/PopcornTimeTV#461]
App version: e3cb96b9077f3e31e3d2a55dc00dc03179627e19
tvOS version: 10.2

#### Expected Behaviour
Audio should automatically sync when selecting an AirPlay speaker instead of the Apple TV audio output.

#### Actual Behaviour
Audio is delayed when selecting an AirPlay speaker instead of the Apple TV audio output.

#### Steps to reproduce the behaviour

From PopcornTime:

1. Launch PopcornTime
2. Launch a movie
3. Swipe down and select "audio"
4. Select an AirPlay speaker listed in the AudioViewController (instead of "Apple TV" by default)
5. Audio and video are out of sync (even not possible to match them by adjusting manual delay)

From Apple TV Settings:

1. Go to Settings
2. Select Audio and Video
3. Select Audio Output
4. Select an AirPlay speaker (instead of "Apple TV" by default)
5. Launch PopcornTime
6. Launch a movie
7. Audio and video are out of sync (even not possible to match them by adjusting manual delay)

_For information, most of other application automatically sync audio and video when AirPlay speaker is selected (I'm quite sure the SDK offer a native feature to handle this, but impossible to find documentation about it)._

**Comment by FlaviaBondJamesBondsHusband** [comment]
> For information, most of other application automatically sync audio and video when AirPlay speaker is selected (I'm quite sure the SDK offer a native feature to handle this, but impossible to find documentation about it).

Normal applications use AVPlayerViewController on tvOS which handles connecting to airplay devices automatically. We however, are using a custom class because AVPlayer doesn't support .mkv files.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Unfortunately this is not possible. In order to have a multi-room experience - i.e. two or more speakers playing the same audio simultaneously - apple set a delay of exactly 2 seconds to give the speaker time to buffer the content it's about to play. Pre-tvOS 10.2, it would have been possible for us to implement our own AirPlay-esque functionality like many third party clients do on mac but apple changed the way airplay streaming works so that is no longer viable.

The reason this works on iOS but not tvOS is because we are using the SDK's `MPVolumeView`, which privately handles connecting to AirPlay devices. This class doesn't exist on tvOS which is why we had to implement our own way of doing it with private frameworks. 

Because we cannot see apple's source code for `AVPlayerViewController`, only the header files, there is no way we can set the delay like they do as it is not publicly documented.

The only way this could be fixed is if they fix it in **libvlc**. People using VLC's own tvOS app and other apps which use the `VLCKit` framework are experiencing [this issue](https://forum.videolan.org/viewtopic.php?t=132370) and Videolan themselves have been aware of [the issue](https://trac.videolan.org/vlc/ticket/16487) for over a year now and have done nothing to fix it (surprise-surprise).
