### ISSUE TITLE
pt-pt

### ISSUE THREAD

**Issue by joaomvfsantos** [PopcornTimeTV/PopcornTimeTV#472]
Based on @CavalcanteLeo Portuguese (Brazil) translation I created the Portuguese (Portugal) translation. 

https://gist.github.com/joaomvfsantos/ab3c285247226ce00fcd3ee9209be4b0

**Comment by FlaviaBondJamesBondsHusband** [comment]
Forking from @CavalcanteLeo is no good because you're missing lots of translations and your language code is wrong [here](https://gist.github.com/joaomvfsantos/ab3c285247226ce00fcd3ee9209be4b0#file-pt_pt-xliff-L12), [here](https://gist.github.com/joaomvfsantos/ab3c285247226ce00fcd3ee9209be4b0#file-pt_pt-xliff-L3), [here](https://gist.github.com/joaomvfsantos/ab3c285247226ce00fcd3ee9209be4b0#file-pt_pt-xliff-L25) and [here](https://gist.github.com/joaomvfsantos/ab3c285247226ce00fcd3ee9209be4b0#file-pt_pt-xliff-L270). Please follow the [Translation Guide](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Translating-Popcorn-Time) and try again
