### ISSUE TITLE
Issue was not answered properly (Subtitles in PT_BR)

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#480]
Have you seen my answer for the issue https://github.com/PopcornTimeTV/PopcornTimeTV/issues/479 ?

You've closed the issue, but haven't solved it.

----
 
**My answer for the issue:**

But you link them. There are subtitles in PT_BR too

PopcornTime is only linking PT_PT, excluding all PT_BR,
Keep in mind they are not the same.

https://github.com/emericg/OpenSubtitlesDownload/wiki/Language-list

**Brazilian portuguese**
SubLanguageID : **'pob'**

**Portuguese**
SubLanguageID : **'por'**

Both are called portuguese, but they are **different**

I have changed the code for me, and worked well, but only for me, thinking of a nation with 220 million ppl, that's a huge country to let it pass 

![captura de tela 2017-05-23 as 14 56 20](https://cloud.githubusercontent.com/assets/1735944/26368441/066cec78-3fc8-11e7-9fe1-17272e9df70a.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
> But you link them. There are subtitles in PT_BR too

If you read [the source](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/PopcornKit/Managers/SubtitlesManager.swift#L63) you would see that we are grabbing every language that has a valid `ISO639` code provided by OpenSubtitles, not their proprietary **SubLanguageID** code. 

We need to use the `ISO639` code for other things which is why we don't just grab any random ID.

**Comment by FlaviaBondJamesBondsHusband** [comment]
> But you link them. There are subtitles in PT_BR too

If you read [the source](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/PopcornKit/Managers/SubtitlesManager.swift#L63) you would see that we are grabbing every language that has a valid `ISO639` code provided by OpenSubtitles, not their proprietary **SubLanguageID** code. 

We need to use the `ISO639` code for other things which is why we don't just grab any random ID.
