### ISSUE TITLE
Version 3.2.0 ipa not available

### ISSUE THREAD

**Issue by maitremiju** [PopcornTimeTV/PopcornTimeTV#509]
Hello

Do you plan on releasing an ipa version on the new version?

**Comment by DJMpc99** [comment]
You can compile it on xcode. 

But devs, can you release the .ipa files for ios and tvos?

**Comment by jardarboge** [comment]
Tried to compile myself, but it did not work, a lot of errors popped up and it said "build failed". If you upload the ipa, it would be great! Someone who might know what I am doing wrong?

**Comment by PerPerJB** [comment]
Tried to compile myself, but it did not work, a lot of errors popped up and it said "build failed". If you upload the ipa, it would be great! Someone who might know what I am doing wrong?

**Comment by FuzzyNutz** [comment]
Same here tried to build and failed

**Comment by angryDuck2** [comment]
I am afraid we cannot distribute signed ipa files, since this is against Apple's developer agreement. You can simply compile it from the source code.

If the source code fails to compile for you, delete the source code and download again.

We will be releasing soon the built .app files for anyone on a jailbroken apple tv

**Comment by DJMpc99** [comment]
You already uploaded a ipa before, why not do it again for the newest version!


Sent from Yahoo Mail for iPhone


On Sunday, February 4, 2018, 6:07 PM, angryDuck2 <notifications@github.com> wrote:


I am afraid we cannot distribute signed ipa files, since this is against Apple's developer agreement. You can simply compile it from the source code.

If the source code fails to compile for you, delete the source code and download again.

We will be releasing soon the built .app files for anyone on a jailbroken apple tv

**Comment by FuzzyNutz** [comment]
The previous dev uploaded the .ipa kuz there where constant build issues for others not sure why it would build for you guys but not for us

**Comment by FuzzyNutz** [comment]
Is there Any way you can build and just revoke the certificate then we can just re sign with our own accounts with Cydia impactor

**Comment by angryDuck2** [comment]
I will try and upload an unsigned ipa for you

**Comment by FuzzyNutz** [comment]
Great thanx !

**Comment by PerPerJB** [comment]
Could you leave a comment here when you have uploaded it?

**Comment by PerPerJB** [comment]
Never mind

**Comment by FuzzyNutz** [comment]
Will the .app be released here ?
