### ISSUE TITLE
Unknown error when opening app on apple tv

### ISSUE THREAD

**Issue by superLost2** [PopcornTimeTV/PopcornTimeTV#510]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

when i open the app i can watch stuff...

#### Actual Behaviour

When i open the app on the apple tv it buffers to get the movie list, but after some time i get the following message: "Unknown error The request timed out.

#### Steps to reproduce the behaviour

1. i installed popcorn time 3.2.0 with impactor
2. opend the app ( got error ) 
3. System reboot 
4. opend app (still error).

**Comment by angryDuck2** [comment]
Hello and sorry for having trouble using the app. Unfortunately, it seems that you are having your ISP blocking the application from contacting the server to get the available torrents. This is an issue between you and your service provider. There is nothing more we can do. I would suggest using a custom DNS server and see if that works for you, otherwise there is nothing we can do!
