### ISSUE TITLE
Downloaded content gets removed (at random?)

### ISSUE THREAD

**Issue by Midifreakz** [PopcornTimeTV/PopcornTimeTV#545]
When an item is downloaded on ATV4, The content gets removed after a system restart.
The 'clear cache on exit' button is unticked

**Comment by popcornMaster** [comment]
Unfortunately the download function in the tvOS application is nothing but a "special effect". tvOS by design does not allow the permanent storage of files bigger than 500kb in total size. Anything larger than this size is just temporarily saved and is up to the operating system's discretion to delete this content when and if it requires more space. This is the reason you might be experiencing movies being deleted at random! [See this reference](https://developer.apple.com/library/content/documentation/General/Conceptual/AppleTV_PG/#//apple_ref/doc/uid/TP40015241-CH12-SW5)
