### ISSUE TITLE
Subtitles out of sync. 

### ISSUE THREAD

**Issue by saveyourskin** [PopcornTimeTV/PopcornTimeTV#551]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...
Play the movie with subtitles in sync 
#### Actual Behaviour

...subtitles are out of sync. And almost every time the subtitle offset increases along the movie. At the beginning in general is about +5 or +6 seconds (never negative). But after I set the offset it will play in sync for some minutes and then I need to adjust the offset a few every 5 or 10 minutes. 
(Also. It could be great if the subtitle offset menu default location start at 0 since scrolling thought all the negative numbers every time is not comfortable)

#### Steps to reproduce the behaviour

1. ...play movie
2. ...select subtitle manually or set the default language in settings(Spanish in my case)
3. ...

**Comment by delut** [comment]
I have an idea on how to fix (or drastically improve) subtitle accuracy. I’d be experimenting on the weekend.

**Comment by GoldenChaos** [comment]
This feature is so poorly implemented. If someone reimplements it properly can it please use the system standard subtitle UI pretty please

**Comment by angryDuck2** [comment]
Unfortunately the native media player does not support avi/mkv or frankly any video format that is not mp4 as well as not supporting srt subtitles! So the current implementation is the only thing we have

**Comment by saveyourskin** [comment]
I don’t know what’s the exact problem. But it worked a lot better before. I don’t remember exactly when it started to happen. But the delay it’s worst on movies than series. 

Also could be great if it can be implemented a way to choose another subtitle if available. Or adding manually a subtitle.

**Comment by Midifreakz** [comment]
I have a few notes and sugestions for improved subtitle support.

1. It  would be great to have an option so a popup appears at the beginning of a show/movie to select subtitles. Kind of how it works in KODI with the opensubtitles plugin. That one is very intuitive! 

2. This one is for ATV. It would be convenient that a simple 'up button' press shows the subtitle sync menu instead or in addition to the 'swipe' command. I've seen a lot of Logitech Harmony and other external remote users complain that there is no way to sync subtitles because the swipe command can not be mapped to external remotes. 

3. I have noticed that when certain shows or movies are streaming, the subtitles are out of sync. However when they are 'downloaded' the subtitle timing fits. 

Just my 2 cents.

**Comment by GoldenChaos** [comment]
@saveyourskin not sure what “before” you’re referring to, but subtitles have always been totally unusable for me since the beginning.

**Comment by coderykw** [comment]
A lot of Chinese subtitles in the movie.

**Comment by popcornMaster** [comment]
The next release will include the ability to download subtitles based on the video downloaded, instead of the movie title, this should help out with the syncing of subtitles
