### ISSUE TITLE
Please help and fix ' The Voice' 

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#56]
Hi some TV shows do not work, including Blue Blood (crashes the app) and Conan (Sounds comes, but nothing happens). The Voice (US) does not work, when clicking the ' tile ' . 

I am sorry, but I am a die hard and soccer for this show. Will somebody fix The Voice? 

Many kudo's!!

**Comment by ynnad696** [comment]
i also see that subtitles for most of tv shows doesn't work, I'm watching Gotham and couple more without any luck..

**Comment by popcornMaster** [comment]
@ynnad696 this is a separate issue, please open a separate one@

@Evhelden if your provider is sky, then you need to configure a vpn on your router, as sky is blocking the website from where we are downloading out torrents, nothing we can do for you! Also if your provider is not sky please try opening this url http://extratorrent.cc/torrent_download/5146526/Now+You+See+Me+2+%282016%29+BRrip+%5BH264%5D.torrent . If this url is blocked then your isp is blocking downloads as well!

**Comment by Evhelden** [comment]
No, my provider is not Sky. I can easily open the torrent from the desktop version of Popcorn

**Comment by tvOSPopcorn** [comment]
@Evhelden Are you able to open the URL in your browser? http://extratorrent.cc/torrent_download/5146526/Now+You+See+Me+2+%282016%29+BRrip+%5BH264%5D.torrent

**Comment by Evhelden** [comment]
Without any problems

**Comment by popcornMaster** [comment]
Mate I am uploading a screenshot of the app streaming the show you are looking for! The streaming of this show is working, admittedly it was not with previous versions but as of 1.0.3.2 it is working perfectly! If you really need to watch this show and since something must have gone terribly wrong with your popcorntime installation please reset your apple tv and reinstall the app! This show is streaming just fine!

![simulator screen shot 04 sep 2016 17 28 31](https://cloud.githubusercontent.com/assets/20759040/18231579/ab2b4a96-72c5-11e6-93b4-c4e4e527ab19.png)

**Comment by Evhelden** [comment]
Wow! You rock! I will go to the new version (I am running 1.0.3.1) and install. Cool!
