### ISSUE TITLE
Indian/Hindi Movies category

### ISSUE THREAD

**Issue by majedsahi** [PopcornTimeTV/PopcornTimeTV#578]
(Sorry this is not an issue but I wasn’t sure where to ask)
Will there ever be a category for Hindi movies? Or a search option to include them? There is a lot of interest and definitely a lot of traffic for sure.

**Comment by popcornMaster** [comment]
Unfortunately we do not have any control over the movies shared from our application, which also concerns our genre selection, hence this is something we cannot help with at all

**Comment by popcornMaster** [comment]
This is decided by the api providers. We currently use [this](https://popcorntime.api-docs.io/api/welcome/introduction)

**Comment by TinyOutsider** [comment]
Apologies if I am asking too many questions.
I am aware that [popcorntime.io](url) is the original site which is now a dead project, but the API is still up. So who manages this API if changes are required. Sorry, I am really trying to get to the bottom of this, because no one on the internet seems to be able to answer this. All I want to know is; if it is possible to add more categories than why don't we have a Bollywood category? They make a ton of movies each year, and there is a lot of demand for it. 
Thanks a lot.
