### ISSUE TITLE
English Subtitles not working

### ISSUE THREAD

**Issue by Chabrall** [PopcornTimeTV/PopcornTimeTV#59]
I'm having problems with english subs not showing up. If I change language, then subs seems to work just fine, but no english subs are being displayed.

**Comment by sasagr** [comment]
this is an old issue that has been never solved. It is happening to me all the time. In the past I understood that it was due to cached subs and that maybe an automatic sub cache clearing could have solved the issue but I never understood if it was going to be implemented and when. Let's hope something can be done

**Comment by maitremiju** [comment]
I can relate to this issue.
All subtitles works but english usually won't show.

**Comment by popcornMaster** [comment]
Bug identified and fix will be implemented on the next version!

**Comment by sasagr** [comment]
while we are waiting for full support on new Xcode e Swift, is it possible to implement this fix for the subtitles? The latest version 46 available with ipa does not have the fix yet.

**Comment by tvOSPopcorn** [comment]
Nope, won't be fixed in the current version. We're prioritising Swift 3 support over a subtitles bug, you're more than welcome to submit a PR though to fix it

**Comment by sasagr** [comment]
sorry but why are you closing this ticked if it is not fixed yet?
I believe you should leave it open so we can keep trace of the status of this issue
