### ISSUE TITLE
Feature Request: Download content in background

### ISSUE THREAD

**Issue by cpvbruno** [PopcornTimeTV/PopcornTimeTV#614]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by popcornMaster** [comment]
Unfortunately this is impossible due to the way Apple enables background content downloading. It is impossible for this to happen given the limitations of iOS

**Comment by cpvbruno** [comment]
Hmm, Im also an iOS developer, did you try all background modes? I guess Netflix use it to download content in background.

In tvOS I don't have many expertise.

**Comment by popcornMaster** [comment]
Well then you should read up more on how background downloads work on iOS/tvOS. It is required that you use NSURLSession objects in order to perform downloads that can be backgrounded. This class, of course, does not support torrent files, or magnet links downloading for that matter, hence background content downloading is impossible. You can read all that here https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background

**Comment by cpvbruno** [comment]
No problems man, that was just a suggestion, if there is no way, there is no way.
