### ISSUE TITLE
Unable to open TV Shows with a period in their titles

### ISSUE THREAD

**Issue by jberglinds** [PopcornTimeTV/PopcornTimeTV#86]
Try opening
* Mr. Robot
* Agents of S.H.I.E.L.D
* Awkward.

None of them opens for me and they all have at least one period in their titles. Gotta have something to do with that.

**Comment by Evhelden** [comment]
With Vinyl the application even stops the application fully.
Flash does not open at all, but does not stop the application.

**Comment by ozkrtech** [comment]
I second this. I've been trying to play "The Flash" series ever since version 0.4? And it never works, not on 0.5 and not even on the new 0.6, it just doesnt do anything when clicking the poster. When you use the search for it theres 2 versions with same "The Flash" name, the old series and the new one, that might explain the problem? The duplicity in names is the culprit?

Oscar Rodriguez
IT Technician

On May 12, 2016, at 5:22 PM, Evhelden <notifications@github.com<mailto:notifications@github.com>> wrote:


With Vinyl the application even stops the application fully.
Flash does not open at all, but does not stop the application.

-

**Comment by ozkrtech** [comment]
I second this. I've been trying to play "The Flash" series ever since version 0.4? And it never works, not on 0.5 and not even on the new 0.6, it just doesnt do anything when clicking the poster. When you use the search for it theres 2 versions with same "The Flash" name, the old series and the new one, that might explain the problem? The duplicity in names is the culprit?

Oscar Rodriguez
IT Technician

On May 12, 2016, at 5:22 PM, Evhelden <notifications@github.com<mailto:notifications@github.com>> wrote:


With Vinyl the application even stops the application fully.
Flash does not open at all, but does not stop the application.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/PopcornTimeTV/PopcornTimeTV/issues/86#issuecomment-218889718>

Oscar Rodriguez
IT Technician

On May 12, 2016, at 5:22 PM, Evhelden <notifications@github.com<mailto:notifications@github.com>> wrote:


With Vinyl the application even stops the application fully.
Flash does not open at all, but does not stop the application.

-

**Comment by Evhelden** [comment]
Noticed that the genres with a ' - '  sign in them (sic-fi and film-noir) don't work.
BTW I recognize the ' double ' issue, cause ' The Voice ' (embarrassing, but I like it) also does not open, like ' Flash ' . I'll share more ' user only ' issues, when possible. I am not capable to program, so need to relay on support for installing. 
There is an app out called ' Movies ' which works well with subtitles and watching movies, including forward and rewind options. It could be helpful to see how they work.

I am happy with the progress this app is making and I will try to be of help.

**Comment by buzzel** [comment]
Im looking into this now. Can't be missing out on the Flash.

**Comment by Evhelden** [comment]
Great.
Another one: Search comes up with different outcomes sometimes. 
Tried ' death in paradise '. Found it earlier and played first episode of 5th season (test run). Worked well. Now this series doesn't show up in the search result list anymore. Search might be random?

**Comment by buzzel** [comment]
The Tv Show API doesnt have a search function, i have to manually fetch all of the shows and then sift through the data. Maybe I am missing a few pieces.

**Comment by buzzel** [comment]
@Evhelden This is all fixed and will be pushed in the next release. You're more than welcome to check out the master branch and have a play with it though.

**Comment by jberglinds** [comment]
@buzzel Was this issue ever really fixed? Still can't open Mr. Robot or Agents of S.H.I.E.L.D.
I believe The Flash might have been a separate bug that you fixed?

**Comment by Evhelden** [comment]
Ah, while somebody is at these series.. How about The Voice US ? :) seriously though...
