### ISSUE TITLE
Alamofire.swift issue

### ISSUE THREAD

**Issue by iAYMANi** [PopcornTimeTV/PopcornTimeTV#93]
http://i.imgur.com/R6X8A6x.png

**Comment by buzzel** [comment]
We don't maintain Alamofire so any of these issues are usually caused by either something on your system or an issue with the library itself. The only few things I suggest trying are this.

- Make sure you are using the latest version of cocoapods (v1.0.0)
- Delete the current PopcornTime release and reclone the repo. (run pod install and pod update)
- Delete all of your derived data and restart Xcode

Unfortunately that issue you are showing lacks a bunch of information as its just an error about something is isn't defined or recognized by swift. 

Hopefully those solve your problem.
