### ISSUE TITLE
Updating Movies and TV Shows

### ISSUE THREAD

**Issue by ArsalanS1** [PopcornTimeTV/PopcornTimeTV#95]
Hi,

I was wondering, as movies and tv shows get added to YTS do we have to keep reinstalling the app or will the actual movies and tv shows update. I understand when new features get added we have to update, but wasnt sure about the actual movies and tv shows catalogue updates.

Cheers

**Comment by RefusedFlow** [comment]
Movies and TV shows are pulled from an API, so they're constantly updated. Installing a newer version of the application doesn't effect the movies and tv shows available. It's a matter of bug fixes and new features you'll get when installing a new version of the application rather than movies and tv shows.

Hope it helps 😄
